CONFIG_FILE: CONFIG.xlsx
LOG_FILE: log.txt
DEBUG_LOG_LEVEL: DEBUG
INFO_LOG_LEVEL: INFO
MAX_RETRIES: 3
DELAY_BETWEEN_RETRIES: 2
PROXY_CHECK_WEBSITE: https://www.example.com
PROXY_RETRY_ON_ERROR: 3
DO_PRINT_DEBUG: true
SENDER_EMAIL: your_email@gmail.com
SENDER_PASSWORD: your_email_password
RECEIVER_EMAIL: receiver_email@gmail.com
SMTP_SERVER: smtp.gmail.com
SMTP_PORT: 587
EXAMPLE_PAGE_URL: https://example.com
PROXY_FILE: config/proxies.txt
DATA_FILE: data.yaml
PROCESS_STARTING_PAGE: https://example.com
API_URL: http://api.name-fake.com
COUNTRY: english-united-states
NAME_FORMAT: "{name}_{surname}_{number}"
NUMBER_OF_ACCOUNTS_TO_BE_CREATED: 10
